
services:
###> doctrine/doctrine-bundle ###
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    depends_on:
      - database
    working_dir: /app
    volumes:
      - ./:/app
      - vendor_data:/app/vendor
    environment:
      APP_ENV: dev
      DATABASE_URL: "mysql://app:root@database:3306/projet_scm?serverVersion=8.0&charset=utf8mb4"
    command: php -S 0.0.0.0:8000 -t public
    ports:
      - "8000:8000"

  database:
    image: mysql:${MYSQL_VERSION:8}-alpine
    environment:
      MYSQL_DB: ${MYSQL_DB:-projet_scm}
      # You should definitely change the password in production
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-root}
      MYSQL_USER: ${MYSQL_USER:-app}
    healthcheck:
      test: ["CMD", "mysqladmin", "-d", "${MYSQL_DB:-app}", "-U", "${MYSQL_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    ports:
      -"3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/mysql/data:rw
###< doctrine/doctrine-bundle ###

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  mysql_data:
###< doctrine/doctrine-bundle ###
